### ISSUE TITLE
stormpath init django django doesn't work

### ISSUE THREAD

**Issue by saimaddali** [stormpath/stormpath-cli#52]
When I do stormpath init django django it throws a DistributionNotFound error 

![image](https://cloud.githubusercontent.com/assets/4591248/18179637/4752199e-7038-11e6-936b-01932c91b22e.png)

**Comment by rdegges** [comment]
How did you install the stormpath CLI project?

**Comment by rdegges** [comment]
The problem here is that this CLI tool isn't installed fully somehow :o
