### ISSUE TITLE
Rewrite to use Click

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-cli#54]
This library has a very complex CLI syntax, and we could simplify the codebase quite a bit by switching from using docopt over to click: http://click.pocoo.org/5/

**Comment by lhazlewood** [comment]
This just changes the underlying implementation, not the actual CLI usage (i.e. what users type), correct?

The current usability is very nice/desirable.  I don't want to force users to use -- flags because a library doesn't support more fluent syntax (as our current CLI supports).

**Comment by rdegges** [comment]
Right, doesn't change any of the flags / etc. Just simplifies the implementation internally.

**Comment by rdegges** [comment]
Actually -- I'm scrapping this since the end goal is going to be to rewrite this using Go. No point in rewriting the internals for no reason.
